### ISSUE TITLE
`undefined method 'success?' for nil:NilClass (NoMethodError)`

### ISSUE THREAD

**Issue by dentarg** [spinels/relaunch#1]
I see this issue from time to time

```shell
$ rerun -x -c -- bundle e puma --log-requests -p 31337

12:05:23 [rerun] Rack-3 launched
12:05:23 [rerun] Rerun (3697) running Rack-3 (3705)
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.2.2-p53) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 3705
* Listening on http://0.0.0.0:31337
Use Ctrl-C to stop
127.0.0.1 - - [16/Jan/2024:12:05:36 +0100] "GET / HTTP/1.1" 200 2 0.0137
r12:09:15 [rerun] Restarting
- Gracefully stopping, waiting for requests to finish
/Users/dentarg/.rubies/3.2.2/lib/ruby/gems/3.2.0/gems/rerun-0.14.0/lib/rerun/runner.rb:185:in `start': undefined method `success?' for nil:NilClass (NoMethodError)

        if status.success?
                 ^^^^^^^^^
	from /Users/dentarg/.rubies/3.2.2/lib/ruby/gems/3.2.0/gems/rerun-0.14.0/lib/rerun/runner.rb:12:in `keep_running'
	from /Users/dentarg/.rubies/3.2.2/lib/ruby/gems/3.2.0/gems/rerun-0.14.0/bin/rerun:18:in `<top (required)>'
	from /Users/dentarg/.rubies/3.2.2/bin/rerun:25:in `load'
	from /Users/dentarg/.rubies/3.2.2/bin/rerun:25:in `<main>'
```

**Comment by dentarg** [comment]
I should not start puma with `-x` as puma doesn't exit, so that could be a clue (but I think I've seen this in other situations too)
